name: Go CI / Docker Build

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Download dependencies
        run: go mod download

      - name: Build Go binary
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o my-finance-app

      - name: Build Docker image
        run: docker build -t finance:${{ github.sha }} .

      # ---------------- OPTIONAL ----------------
      # Push image to Docker Hub
      # ------------------------------------------
#      - name: Login to Docker Hub
#        if: github.ref == 'refs/heads/main'
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_USERNAME }}
#          password: ${{ secrets.DOCKER_PASSWORD }}
#
#      - name: Push Docker image
#        if: github.ref == 'refs/heads/main'
#        run: |
#          docker tag finance:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/finance:latest
#          docker push ${{ secrets.DOCKER_USERNAME }}/finance:latest
